export const ROUTES = {
  SPLASH: '/',
  ONBOARDING: '/onboarding',
  LOGIN: '/login',
  SIGNUP: '/signup',
  HOME: '/home',
  MAP: '/map',
  TRIP_PLANNER: '/plan-trip',
  TRIP_DETAILS: '/trip-details',
  ASSISTANT: '/assistant',
  EMERGENCY: '/emergency',
  SOS_CONFIRM: '/sos-confirm',
  ALERTS: '/alerts',
  PROFILE: '/profile',
  ADMIN_DASHBOARD: '/admin',
  MY_TRIPS: '/my-trips',
  SAFETY_CHECK: '/safety-check',
  LIVE_TRACKING: '/live-tracking',
};
